### ISSUE TITLE
Changing sort with a namespace selected looses the namespace

### ISSUE THREAD

**Issue by anoteboom** [remko/dsadmin#5]
When I select a namespace, i can see all the data in that namespace.
When I then click on the tableheader to change the order, the namespace resets back to the default namespace.

The /namespaces/namespaceID/ part in the url seems to be missing.
When I manually add this namespace part to the url, is see the expected data in the expected order.

I just noticed:  The same issue seem to occur when clicking on the next/previous buttons or selecting a different rows per page.

Thank you for creating this great tool. This really is the best tool I found.

**Comment by remko** [comment]
Good catch, thanks!

Should be fixed in v0.18.1.
